### ISSUE TITLE
About device

### ISSUE THREAD

**Issue by aveliks** [daguix/cordova-plugin-caribe-laser-barcode-scanner#1]
Hi!
Is it device 
https://ru.aliexpress.com/store/product/Caribe-PL-40LAb035-Android-industrial-1d-barcode-scanner-wireless-data-collection-terminal-with-gps/2165079_32546927163.html?detailNewVersion=&categoryId=200003332&spm=2114.12010608.0.0.1IMTKf
supported by Your plugin?

If no, can You send link for right choice with good supporting by Your plugin?

**Comment by daguix** [comment]
Hi,

  Yes, my plugin is for this model. You can also download the SDK at this dropbox address with an example if you want to code natively. I got it from the seller on aliexpress.
https://www.dropbox.com/s/t9qge3bqn4tftxb/TestScan.zip?dl=0 <https://www.dropbox.com/s/t9qge3bqn4tftxb/TestScan.zip?dl=0>

Regards.
